language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip --version
  - pip install coveralls pytest-cov pytest
  - pip install --upgrade pytest
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov sequenticon --cov-report term-missing

after_success:
  - coveralls
